name: Solscan Scraper

on:
  workflow_dispatch: # This enables API/manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }} # Use PAT for checkout to allow pushing

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Latest LTS version as of March 2025

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libatk-bridge2.0-0 libcups2-dev libxkbcommon-x11-0 libxcomposite-dev libxrandr-dev libxdamage-dev

      - name: Run Solscan scraper
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: timeout 10m node extract-headless.js --no-sandbox --disable-gpu --disable-dev-shm-usage || echo "Script timed out after 10 minutes"

      - name: Commit and push seen-transactions.json
        if: always() # Run even if the previous step fails
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add seen-transactions.json || echo "No seen-transactions.json to add"
          git commit -m "Update seen-transactions.json [skip ci]" || echo "Nothing to commit"
          git push || echo "Nothing to push"